---
title: "Data Tidying"
author: "Andy Barclay"
date: "May 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(dplyr)
library(tidyr)
```

This reads in the data from [Here](https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1)

```{r catch data}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```

Removed unwanted columns
```{r remove unwanted cols}

catch_df<-catch_df %>% 
  select(-All,-notesRegCode)%>% 
  gather(key=species,value=catch,Chinook,Sockeye,Coho,Pink,Chum)%>% 
  rename(Catch_Thousands=catch,Species=species)
 
```

Remove "I" in catch and multiply by 1000

```{r fix catch col}

catch_df<-catch_df%>%
  mutate(Catch_Thousands=ifelse(Catch_Thousands=="I",1,Catch_Thousands)) %>%
  mutate(Catch_Thousands=as.integer(Catch_Thousands)) %>%
  mutate(Catch=Catch_Thousands*1000)

```

#Analysis
```{r annual catch}
Annual_catch<-catch_df %>% 
  filter(Species=="Chinook") %>% 
  group_by(Region,Year) %>% 
  summarise(Mean_Catch=mean(Catch),num_obs=n()) %>% 
  arrange(desc(Mean_Catch))
```

#Add region definitions
```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),
                        stringsAsFactors = FALSE)
```
##Select columns from region definition DF
```{r}
region_defs<-region_defs %>% 
  select(code,mgmtArea) %>% 
  rename(Region=code, Region_Name=mgmtArea)
```
##Join catch data with region names
```{r}

catch_joined <- left_join(catch_df,region_defs,by = "Region")


```


